In [8]:
import numpy as np

In [9]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [18]:
def sig(z):
    return (1/(1 + np.exp(-z)))

In [40]:
w0 = 2 * np.random.random((2,2)) - 1
b0 = 2 * np.random.random((1,2)) - 1

wh = 2 * np.random.random((2,1)) -1
bh = 2 * np.random.random((1,1)) - 1

In [41]:
output0 = X
outputh = sig(np.dot(output0,w0) + b0)
output = sig(np.dot(outputh,wh) + bh)

In [44]:
a = np.dot(output0,w0) + b0
a

array([[ 0.45087275, -0.67713865],
       [ 0.33424759, -0.31420854],
       [ 1.26399219,  0.14256436],
       [ 1.14736703,  0.50549446]])

In [49]:
b =1/(np.exp(-a)+1)
b

array([[0.61084672, 0.33690023],
       [0.58279252, 0.42208782],
       [0.77971258, 0.53558085],
       [0.75902967, 0.62374968]])

In [52]:
c =sig(np.dot(outputh,wh) + bh)
c.shape

(4, 1)

In [51]:
output

array([[0.60003799],
       [0.59691865],
       [0.60243088],
       [0.59955327]])

In [5]:
g = np.array([0,0,0,1])
f = g.T
g.shape

(4,)

#### Neural network implementation for general network with hidden layers

In [16]:
import numpy as np

In [17]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[0]])

X.shape,Y.shape

((4, 2), (4, 1))

In [18]:
def derevativeSig(z):
    return sig(z) * (1-sig(z))

In [19]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [20]:
wh = 2 * np.random.random((2,2)) - 1
bh = 2 * np.random.random((1,2)) - 1

wo = 2 * np.random.random((2,1)) - 1
bo = 2 * np.random.random((1,1)) - 1

lr = 0.1

In [21]:
  for itr in range(10000):
    #forward propagation with hidden layers
    output0 = X #output of input layer is X

    inputHidden = np.dot(output0,wh) + bh
    outputHidden = sig(inputHidden)

    inputForOutputLayer = np.dot(outputHidden,wo) + bo
    output = sig(inputForOutputLayer) #this is predicted output

    #Back propagation with hidden output layer
    first_term_output_layer = output - Y
    second_term_output_layer = derevativeSig(inputForOutputLayer)
    first_two_term_output_layer = first_term_output_layer * second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_term_output_layer, wo.T)
    second_term_hidden_layer = derevativeSig(inputHidden)
    first_two_term_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    #chnage = first_two_term of current layer * output of previous layer
    changes_output_layer = np.dot(outputHidden.T, first_two_term_output_layer) 
    changes_output_layer_bias = np.sum(first_two_term_output_layer, axis = 0, keepdims=True) #keeping the dimension same

    changes_hidden_layer = np.dot(output0.T, first_two_term_hidden_layer) 
    changes_hidden_layer_bias = np.sum(first_two_term_hidden_layer, axis = 0, keepdims=True)

    wo =wo - lr*changes_output_layer
    bo = bo - lr*changes_output_layer_bias

    wh =wh - lr*changes_hidden_layer
    bh = bh - lr*changes_hidden_layer_bias 

#after updating the weights 10000 time,lets print the output
output0 = X #output of input layer is X

inputHidden = np.dot(output0,wh) + bh
outputHidden = sig(inputHidden)

inputForOutputLayer = np.dot(outputHidden,wo) + bo
output = sig(inputForOutputLayer) #this is predicted output
output, wh, bh, wo, bo

(array([[0.05730379],
        [0.95234099],
        [0.9484171 ],
        [0.05132579]]),
 array([[-5.63813717,  4.59819663],
        [ 5.72786554, -4.92299832]]),
 array([[-3.34847063, -2.55604971]]),
 array([[7.16954143],
        [7.32287895]]),
 array([[-3.57115119]]))